---
- name: Get OS type
  debug:
    var: ansible_facts.distribution

- name: Get OS type
  debug:
    var: ansible_user

- name: Install
  apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - python3-dev
      - python3-pip
      - acl



- name: Install  python package
  pip:
    name: psycopg2
