---
# - name: Create site.conf
#   template:
#      src: site.conf
#      dest: '{{ nginx_docker_workdir}}/nginx/files/site.conf'

- name: Get OS type
  debug:
    var: ansible_facts.distribution

- name: Get OS type
  debug:
    var: ansible_user

- name: Install
  apt:
    name:
      - unzip
      - virtualenv

- name: delete
  file:
    path: /opt/app
    state: absent

# - name: delete
#   file:
#     path: /opt/conf.yml
#     state: absent

- name: create
  file:
    path: /opt/app
    state: directory

- name: copy
  copy:
    src: app.zip
    dest: /opt



- name: create
  unarchive:
    src: /opt/app.zip
    dest: /opt
    remote_src: yes

#CMD npm install

# - name: Build an image and push it to a private repo
#   docker_image:
#     name: nodejs
#     build:
#       path: '{{ nginx_docker_workdir }}/nginx/'
#     force_source: yes
#     source: build

# - name: Finer container restart/update control
#   docker_container:
#     name: "{{ containers['nginx'].name }}"
#     image: nodejs
#     hostname: "{{ containers['nginx'].hostname }}"
#     networks: "{{containers['nginx'].networks }}"
#     ports: "{{containers['nginx'].ports  }}"
#     mounts: "{{ containers['nginx'].mounts }}"
#     state: started
   # volumes:
   #    - /opt
